### ISSUE TITLE
작성된 ERD를 기반으로 Entity 및 DAO를 생성한다.

### ISSUE THREAD

**Issue by kwakmins** [kawkmin/wanted-pre-onboarding-backend#3]
## 📝 Description

작성된 ERD를 기반으로 Entity 및 DAO를 생성합니다.

## ☑️ TODO

- [x] 사용자 관련 Entity 및 DAO 생성
- [x] 회사 관련 Entity 및 DAO 생성
- [x] 채용공고 관련 Entity 및 DAO 생성
